# -*- coding: utf-8 -*-
"""brownian_motion_cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPLrnCXwOPFFyl-SdGplOfUTCP02d3RP
"""

import argparse
from brownian_motion_simulation.core import motion_2d, motion_3d, collecting_data_2d, collecting_data_3d, plot_2d, plot_3d

def main() -> None:
  parser = argparse.ArgumentParser(
        description="This script simulates 2D and 3D Brownian motion over multiple trials.step length is given by the user. In this model, a step in the x-direction is treated as a 'favor', and the y-direction as the 'odd' — a conceptual pairing used to define how each step behaves. Signs are then randomly assigned to simulate direction. The code also can simulate more than 1 random brownian motion, each one for a trial."
    )
  parser.add_argument(
        "dimension",
        choices=["2D", "3D"],
        type=str,
        
        help="dimension of the simulation",
    )
  parser.add_argument(
        "trial_number",
        type=int,
        help="number of trials",
    )
  parser.add_argument(
        "number_of_steps",
        type=int,
        help="number of steps",
    )
  parser.add_argument(
        "step_length",
        type=float,
        help="step length",

    )
  args = parser.parse_args()

  if args.dimension == "2D":

    x_data_every_trial, y_data_every_trial= collecting_data_2d(args.trial_number, motion_2d,args.number_of_steps, args.step_length)
    plot_2d(x_data_every_trial, y_data_every_trial)

  elif args.dimension == "3D":

    x_data_every_trial, y_data_every_trial, z_data_every_trial = collecting_data_3d(args.trial_number, motion_3d,args.number_of_steps, args.step_length)
    plot_3d(x_data_every_trial, y_data_every_trial, z_data_every_trial)

if __name__ == "__main__":
    main()