# -*- coding: utf-8 -*-
"""brownian_motion_core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcBKP5me5VXj7yB61GILqhcX-RvdlfSQ
"""

'''brownian motion
This script simulates 2D and 3D Brownian motion over multiple trials.
step length is given by the user.
In this model, a step in the x-direction is treated as a 'favor', and the y-direction as the 'odd' — a conceptual pairing used to define how each step behaves. Signs are then randomly assigned to simulate direction.
The code also can simulate more than 1 random brownian motion, each one for a trial.'''

import random
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

'''2D'''

#each trial
#the data points for each brownian motion/ each trial
def motion_2d(n, length_of_step) :
  i = 0
  x_axis_distance = 0
  y_axis_distance = 0
  x_data = []
  y_data = []

  for i in range(n) :
    r_1=random.uniform(-1,1)#the probaility of taking a step in x direction is (0,1). we assign + and - sign to include both left and right direction.
    #print(r_1)
    x= r_1*length_of_step
    x_axis_distance +=x
    x_data.append(x_axis_distance)# to get the x value randomly for each point in a brownian motion

    if r_1<0:#if the probability in x direction is negetive or in the left
      r_2 = random.choice([-(1+r_1) , (1+r_1)])# 1+r_1 has range (0,1) and is the probabilty of a step in y direction without considering up and down. so then we randomly chose the direction + or - as up and down.
    else:
      r_2 = random.choice([-(1-r_1) , (1-r_1)])#similarly the probability of a step in y direction  will be 1- r_1 without up or down direction. then we randomely assign up and down.

  #i have randomely chosen the probability of a step in x direction  and by multiplying with the length of step we get the distance in x direction. but it doesnt mention if positive x or negetive x, that is why the range is taken from -1 to 1 to imply the 2 direction. but the probability of a step in y direction depends only on the respective value of probability of a step in x direction. then again it doesnt specify the direction of y. so we again randomly chose 'up' or 'down' by using + and - sign. The goal here is to just get a step with the fixed legnth provided in a random direction.
    #print (r_2)
    y= r_2*length_of_step
    y_axis_distance +=y
    y_data.append(y_axis_distance)# to get the respective y values

  #print(x_data)
  #print(y_data)
  return (x_data, y_data)# the points of a brownian path



#showing all the trial. we collect every brownian motion here.
def collecting_data_2d(trial,data_generating_function,*args):
#assignment
   x_data_every_trial=[]
   y_data_every_trial=[]
   j=0

#loop for each trial
   for j in range(trial):
    x,y=data_generating_function(*args)
    x_data_every_trial.append(x)
    y_data_every_trial.append(y)
   #print(x_data)
   #print(y_data)
   return x_data_every_trial, y_data_every_trial



#plotting
def plot_2d(x_data_every_trial, y_data_every_trial) :

  for x_data in x_data_every_trial:
    index = x_data_every_trial.index(x_data)
    y_data = y_data_every_trial[index]
    plt.plot(x_data, y_data)
    plt.xlabel("X", fontsize=12, fontweight='bold', color='black')
    plt.ylabel("Y", fontsize=12, fontweight='bold', color='blue')
    plt.title("brownian motion path", loc='left', fontdict={'fontsize': 14, 'color': 'black'})
  plt.show()

'''3D'''
#each trial
#the data points for each brownian motion/ each trial
def motion_3d(n, length_of_step) :

  x_axis_distance = 0
  y_axis_distance = 0
  z_axis_distance = 0
  x_data = []
  y_data = []
  z_data = []

  for i in range(n) :
    r_1=random.uniform(-1,1)#the probaility of taking a step in x direction is (0,1). we assign + and - sign to include both left and right direction.
    #print(r_1)
    x= r_1*length_of_step
    x_axis_distance +=x
    x_data.append(x_axis_distance)# to get the x value randomly for each point in a brownian motion

    if r_1<0:#if the probability in x direction is negetive or in the left
      r_2 = random.uniform(-(1+r_1) , (1+r_1))# 1+r_1 has range (0,1) and is the probabilty of a step in y direction without considering up and down. so then we randomly chose the direction + or - as up and down.
    else:
      r_2 = random.uniform(-(1-r_1) , (1-r_1))#similarly the probability of a step in y direction  will be 1- r_1 without up or down direction. then we randomely assign up and down.

  #i have randomely chosen the probability of a step in x direction  and by multiplying with the length of step we get the distance in x direction. but it doesnt mention if positive x or negetive x, that is why the range is taken from -1 to 1 to imply the 2 direction. but the probability of a step in y direction depends only on the respective value of probability of a step in x direction. then again it doesnt specify the direction of y. so we again randomly chose 'up' or 'down' by using + and - sign. The goal here is to just get a step with the fixed legnth provided in a random direction.
    #print (r_2)
    y= r_2*length_of_step
    y_axis_distance +=y
    y_data.append(y_axis_distance)# to get the respective y values

    r_3 = 1- abs(r_1)-abs(r_2)
    z= r_3*length_of_step
    z_axis_distance +=z
    z_data.append(z_axis_distance)

  #print(x_data)
  #print(y_data)
  return (x_data, y_data, z_data)# the points of a brownian path



#showing all the trial. we collect every brownian motion here.
def collecting_data_3d(trial, data_generating_function,*args):
#assignment
   x_data_every_trial=[]
   y_data_every_trial=[]
   z_data_every_trial=[]
   j=0

#loop for each trial
   for j in range(trial):
    x,y,z=data_generating_function(*args)
    x_data_every_trial.append(x)
    y_data_every_trial.append(y)
    z_data_every_trial.append(z)
   #print(x_data)
   #print(y_data)
   return x_data_every_trial, y_data_every_trial, z_data_every_trial



#plotting
def plot_3d( x_data_every_trial, y_data_every_trial, z_data_every_trial ):



  for x_data, y_data, z_data in zip(x_data_every_trial, y_data_every_trial, z_data_every_trial):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot(x_data, y_data, z_data)  # Plot one trial at a time

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_title("3D Brownian Motion Path")
  plt.show()